version: "3.9"
services:
  db_games:
    image: postgres:latest
    container_name: db_games
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    networks:
      - fmba-bridge
    ports:
      - 5434:5432
    volumes:
      - db:/var/lib/postgres

  app_games:
    image: prestoshat-backend/app_games:1.0
    container_name: app_games
    restart: on-failure
    depends_on:
      - db_games
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8084:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_games:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update      
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
    networks:
      - fmba-bridge

networks:
  fmba-bridge:
    driver: bridge

volumes:
  db: