version: "3.9"
services:
  db_cliente:
    image: postgres:latest
    container_name: db_cliente
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    networks:
      - fmba-bridge
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgres

  app_cliente:
    image: prestoshat-backend/cliente:1.0
    container_name: app_cliente
    restart: on-failure    
    build:      
      dockerfile: Dockerfile
      context: .
    ports:
      - "8085:8080"
    environment: 
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_cliente:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update      
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect 
    networks:
      - fmba-bridge

networks:
  fmba-bridge:
    driver: bridge
    
volumes:
  db: